from __future__ import annotations

import os
import smtplib
from datetime import date
from email.message import EmailMessage
from typing import Any

from backend.dashboard_service import trader_detail
from backend.news_service import load_dotenv


DEFAULT_STRATEGY = "watchlist-variable-news-optimized-experimental"
DEFAULT_RECIPIENT = "nisargdave@hotmail.com"


def env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().casefold() in {"1", "true", "yes", "on"}


def money(value: object) -> str:
    if value is None:
        return "-"
    try:
        return f"${float(value):,.2f}"
    except (TypeError, ValueError):
        return str(value)


def pct(value: object) -> str:
    if value is None:
        return "-"
    try:
        return f"{float(value):+.2f}%"
    except (TypeError, ValueError):
        return str(value)


def number(value: object) -> str:
    if value is None:
        return "-"
    try:
        return f"{float(value):,.4f}".rstrip("0").rstrip(".")
    except (TypeError, ValueError):
        return str(value)


def line_items(rows: list[dict[str, Any]], formatter) -> list[str]:
    if not rows:
        return ["  None."]
    return [formatter(row) for row in rows]


def format_order(row: dict[str, Any]) -> str:
    action = str(row.get("action", "")).upper()
    ticker = row.get("ticker", "-")
    signal = row.get("entry_signal", "-")
    observed = row.get("signal_observed_date", "-")
    amount = money(row.get("usd_amount")) if row.get("action") == "buy" else "full position"
    quantity = number(row.get("quantity"))
    quantity_text = "" if row.get("action") == "buy" else f" | qty {quantity}"
    return f"  {action} {ticker} | signal {signal} | observed {observed} | amount {amount}{quantity_text}"


def format_holding(row: dict[str, Any]) -> str:
    return (
        f"  HOLD {row.get('ticker', '-')} | entry {row.get('entry_date', '-')} "
        f"({row.get('entry_signal', '-')}) | value {money(row.get('current_value'))} | "
        f"P/L {money(row.get('gain_loss'))} ({pct(row.get('return_pct'))}) | "
        f"daily {pct(row.get('daily_change_pct'))}, 5D {pct(row.get('five_day_change_pct'))}, "
        f"monthly {pct(row.get('monthly_change_pct'))}"
    )


def format_realized(row: dict[str, Any]) -> str:
    return (
        f"  SOLD {row.get('ticker', '-')} | {row.get('entry_date', '-')} to {row.get('exit_date', '-')} | "
        f"P/L {money(row.get('gain_loss'))} ({pct(row.get('return_pct'))})"
    )


def build_daily_instructions_body(detail: dict[str, Any]) -> str:
    pending = list(detail.get("pending_next_close_orders") or [])
    holdings = list(detail.get("positions") or [])
    realized = list(detail.get("realized_positions") or [])[:15]

    lines = [
        f"Daily instructions for {detail.get('investor', DEFAULT_STRATEGY)}",
        f"Window: {detail.get('from_date')} to {detail.get('to_date')}",
        "",
        str(detail.get("execution_convention") or "Signals are observed after close and executed at the next available close."),
        "",
        "Pending next-close orders",
        *line_items(pending, format_order),
        "",
        "Current holdings",
        *line_items(holdings, format_holding),
        "",
        "Recently realized positions",
        *line_items(realized, format_realized),
        "",
        "Portfolio summary",
        f"  Current value: {money(detail.get('current_value'))}",
        f"  Gain / loss: {money(detail.get('gain_loss'))}",
        f"  Return: {pct(detail.get('return_pct'))}",
        f"  Daily: {pct(detail.get('daily_change_pct'))}",
        f"  5D: {pct(detail.get('five_day_change_pct'))}",
        f"  Monthly: {pct(detail.get('monthly_change_pct'))}",
        "",
        "Generated by the Paper Trading Dashboard refresh.",
    ]
    return "\n".join(lines)


def smtp_configured() -> tuple[bool, dict[str, str]]:
    load_dotenv()
    config = {
        "host": os.environ.get("SMTP_HOST", "").strip(),
        "port": os.environ.get("SMTP_PORT", "587").strip(),
        "username": os.environ.get("SMTP_USERNAME", "").strip(),
        "password": os.environ.get("SMTP_PASSWORD", "").strip(),
        "from_email": (
            os.environ.get("EMAIL_FROM", "").strip()
            or os.environ.get("SMTP_USERNAME", "").strip()
        ),
        "recipient": (
            os.environ.get("DAILY_INSTRUCTIONS_RECIPIENT", "").strip()
            or DEFAULT_RECIPIENT
        ),
        "strategy": (
            os.environ.get("DAILY_INSTRUCTIONS_STRATEGY", "").strip()
            or DEFAULT_STRATEGY
        ),
    }
    required = ("host", "port", "username", "password", "from_email", "recipient")
    return all(config[name] for name in required), config


def send_daily_instructions(
    start: date,
    end: date | None,
    apply_wealthsimple_fx_fees: bool = False,
) -> dict[str, object]:
    load_dotenv()
    if not env_bool("DAILY_INSTRUCTIONS_EMAIL_ENABLED"):
        return {
            "status": "skipped",
            "reason": "DAILY_INSTRUCTIONS_EMAIL_ENABLED is not true",
            "recipient": DEFAULT_RECIPIENT,
            "strategy": DEFAULT_STRATEGY,
        }

    configured, config = smtp_configured()
    if not configured:
        return {
            "status": "skipped",
            "reason": "SMTP settings are incomplete",
            "recipient": config["recipient"],
            "strategy": config["strategy"],
        }

    detail = trader_detail(
        config["strategy"],
        start,
        end,
        apply_wealthsimple_fx_fees=apply_wealthsimple_fx_fees,
    )
    message = EmailMessage()
    message["Subject"] = f"Daily instructions: {config['strategy']} as of {detail.get('to_date')}"
    message["From"] = config["from_email"]
    message["To"] = config["recipient"]
    message.set_content(build_daily_instructions_body(detail))

    try:
        port = int(config["port"])
    except ValueError as exc:
        raise ValueError("SMTP_PORT must be a number") from exc

    timeout = int(os.environ.get("SMTP_TIMEOUT_SECONDS", "20"))
    with smtplib.SMTP(config["host"], port, timeout=timeout) as smtp:
        if env_bool("SMTP_USE_TLS", default=True):
            smtp.starttls()
        smtp.login(config["username"], config["password"])
        smtp.send_message(message)

    return {
        "status": "sent",
        "recipient": config["recipient"],
        "strategy": config["strategy"],
        "to_date": detail.get("to_date"),
        "pending_orders": len(detail.get("pending_next_close_orders") or []),
        "holdings": len(detail.get("positions") or []),
    }
